### ISSUE TITLE
feature request: replace terraform data block name

### ISSUE THREAD

**Issue by toyamagu-2021** [suzuki-shunsuke/tfmv#34]
It would be great if we can change terraform data block name.

1. change data block name
2. change reference of data block

**Comment by suzuki-shunsuke** [comment]
Thank you for your proposal.
It looks good.

- https://github.com/suzuki-shunsuke/tfmv/pull/35

**Comment by suzuki-shunsuke** [comment]
🎉 https://github.com/suzuki-shunsuke/tfmv/releases/tag/v0.2.2
